language: node_js
node_js: node
branches:
  only: master
env:
  global:
    secure: qPnAQgbNjFG2TyX2ytI9sHnjlcxllAFuQfX3MM+af+BxAq2X++MaEKviqW2NqVP47ivSD85KVeH3eteHT+Edh5IghIxqLJ72OiZ3lll0ofsu9opfs23TU+Z3FSN0AuZK+5eLfdNIuoRGSX+xw30wFnD/fOqeDeTBgVWT457lOkw=
sudo: true
script:
  - set -e # If one script throws an error, all scripts end
  - git config --global user.name "Travis CI Deploy"
  - git config --global user.email "noreply@travis-ci.org"
  - pushd generator
  - npm i
  - node index
  - popd
  - git add . # `git commit -a` does not add unversioned files
  - git commit -m "build [skip ci]"
  - git push --quiet https://${GITHUB_TOKEN}@github.com/ArtskydJ/josephdykstra.com master:master
