language: node_js
node_js: node
branches:
  only: master
env:
  global:
    secure: qPnAQgbNjFG2TyX2ytI9sHnjlcxllAFuQfX3MM+af+BxAq2X++MaEKviqW2NqVP47ivSD85KVeH3eteHT+Edh5IghIxqLJ72OiZ3lll0ofsu9opfs23TU+Z3FSN0AuZK+5eLfdNIuoRGSX+xw30wFnD/fOqeDeTBgVWT457lOkw=
sudo: true
script:
  - set -e # If one script throws an error, all scripts end
  - sudo apt-get install -y wkhtmltopdf
  - QT_QPA_PLATFORM="offscreen phantomjs rasterize.js 2i8zaNg04d9B41Zir2kT3J/output.html 2i8zaNg04d9B41Zir2kT3J.png" # https://github.com/ariya/phantomjs/issues/14376#issuecomment-236213526
  #- sudo sh -e /etc/init.d/xvfb start # Avoid "QXcbConnection: Could not connect to display" error (I hope)
  - git config --global user.name "Travis CI Deploy"
  - git config --global user.email "noreply@travis-ci.org"
  - pushd generator
  - npm i
  - git clone https://github.com/ArtskydJ/josephdykstra.com josephdykstra.com_gh-pages
  - pushd josephdykstra.com_gh-pages
  - git checkout gh-pages
  - cp resume.pdf ../../content/resume.pdf
  - npm run build # Runs the build script from ../generator/package.json
  - rm ../../content/resume.pdf
  - git add . # `git commit -a` does not add unversioned files
  - git commit -m "build"
  - git push --quiet https://${GITHUB_TOKEN}@github.com/ArtskydJ/josephdykstra.com gh-pages:gh-pages
  - popd
  - popd
