name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and run script
        run: |
          cd generator
          npm install
          node index

      - name: Commit and push changes
        run: |
          git config --global user.name "ArtskydJ"
          git config --global user.email "josephdykstra@gmail.com"
          git add .
          git commit -m "build [skip ci]"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/ArtskydJ/josephdykstra.com master:master
